[env:esp32dev]

platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    milesburton/DallasTemperature@^3.9.0
    paulstoffregen/OneWire@^2.3.7
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.0
    sandeepmistry/LoRa@^0.7.0